Gem::Specification.new do |s|
  s.name = "mizuho"
  s.version = "0.9.5"
  s.summary = "Mizuho documentation formatting tool"
  s.email = "hongli@phusion.nl"
  s.homepage = "http://github.com/FooBarWidget/mizuho/tree/master"
  s.description = "A documentation formatting tool. Mizuho converts Asciidoc input files into nicely outputted HTML, possibly one file per chapter. Multiple templates are supported, so you can write your own."
  s.has_rdoc = false
  s.executables = ["mizuho"]
  s.authors = ["Hongli Lai"]
  s.add_dependency("hpricot")
  
  s.files = [
      "README.markdown", "LICENSE.txt", "mizuho.gemspec", "Rakefile",
      "bin/mizuho",
      "lib/mizuho/chapter.rb",
      "lib/mizuho/generator.rb",
      "lib/mizuho/heading.rb",
      "lib/mizuho/parser.rb",
      "lib/mizuho/template.rb",
      "test/parser_spec.rb",
      "test/spec_helper.rb",
      "templates/asciidoc.css",
      "templates/asciidoc.html.erb",
      "templates/manualsonrails.css",
      "templates/manualsonrails.html.erb",
      
      "asciidoc/a2x", "asciidoc/asciidoc.conf", "asciidoc/asciidoc.py", "asciidoc/BUGS", "asciidoc/BUGS.txt", "asciidoc/CHANGELOG", "asciidoc/CHANGELOG.txt", "asciidoc/common.aap", "asciidoc/configure", "asciidoc/configure.ac", "asciidoc/COPYING", "asciidoc/COPYRIGHT", "asciidoc/dblatex", "asciidoc/dblatex/asciidoc-dblatex.sty", "asciidoc/dblatex/asciidoc-dblatex.xsl", "asciidoc/dblatex/dblatex-readme.txt", "asciidoc/doc", "asciidoc/doc/a2x.1", "asciidoc/doc/a2x.1.txt", "asciidoc/doc/article.css-embedded.html", "asciidoc/doc/article.html", "asciidoc/doc/article.pdf", "asciidoc/doc/article.txt", "asciidoc/doc/asciidoc-revhistory.xml", "asciidoc/doc/asciidoc.1", "asciidoc/doc/asciidoc.1.css-embedded.html", "asciidoc/doc/asciidoc.1.css.html", "asciidoc/doc/asciidoc.1.html", "asciidoc/doc/asciidoc.1.txt", "asciidoc/doc/asciidoc.conf", "asciidoc/doc/asciidoc.css-embedded.html", "asciidoc/doc/asciidoc.css.html", "asciidoc/doc/asciidoc.dict", "asciidoc/doc/asciidoc.html", "asciidoc/doc/asciidoc.txt", "asciidoc/doc/asciimathml.txt", "asciidoc/doc/book-multi.css-embedded.html", "asciidoc/doc/book-multi.html", "asciidoc/doc/book-multi.txt", "asciidoc/doc/book.css-embedded.html", "asciidoc/doc/book.html", "asciidoc/doc/book.txt", "asciidoc/doc/customers.csv", "asciidoc/doc/docbook-xsl.css", "asciidoc/doc/faq.txt", "asciidoc/doc/images", "asciidoc/doc/latex-backend.html", "asciidoc/doc/latex-backend.txt", "asciidoc/doc/latexmath.txt", "asciidoc/doc/latexmathml.txt", "asciidoc/doc/main.aap", "asciidoc/doc/music-filter.html", "asciidoc/doc/music-filter.pdf", "asciidoc/doc/music-filter.txt", "asciidoc/doc/source-highlight-filter.html", "asciidoc/doc/source-highlight-filter.pdf", "asciidoc/doc/source-highlight-filter.txt", "asciidoc/docbook-xsl", "asciidoc/docbook-xsl/asciidoc-docbook-xsl.txt", "asciidoc/docbook-xsl/chunked.xsl", "asciidoc/docbook-xsl/common.xsl", "asciidoc/docbook-xsl/fo.xsl", "asciidoc/docbook-xsl/htmlhelp.xsl", "asciidoc/docbook-xsl/manpage.xsl", "asciidoc/docbook-xsl/text.xsl", "asciidoc/docbook-xsl/xhtml.xsl", "asciidoc/docbook.conf", "asciidoc/examples", "asciidoc/examples/website", "asciidoc/examples/website/a2x.1.html", "asciidoc/examples/website/a2x.1.txt", "asciidoc/examples/website/asciidoc-docbook-xsl.html", "asciidoc/examples/website/asciidoc-docbook-xsl.txt",
      "asciidoc/examples/website/asciidoc-graphviz-sample.txt", "asciidoc/examples/website/ASCIIMathML.js", "asciidoc/examples/website/asciimathml.txt", "asciidoc/examples/website/build-website.sh", "asciidoc/examples/website/CHANGELOG.html", "asciidoc/examples/website/CHANGELOG.txt", "asciidoc/examples/website/customers.csv", "asciidoc/examples/website/downloads.html", "asciidoc/examples/website/downloads.txt", "asciidoc/examples/website/faq.html", "asciidoc/examples/website/faq.txt", "asciidoc/examples/website/images", "asciidoc/examples/website/index.html", "asciidoc/examples/website/index.txt", "asciidoc/examples/website/INSTALL.html", "asciidoc/examples/website/INSTALL.txt", "asciidoc/examples/website/latex-backend.html", "asciidoc/examples/website/latex-backend.txt", "asciidoc/examples/website/LaTeXMathML.js", "asciidoc/examples/website/latexmathml.txt", "asciidoc/examples/website/layout1.conf", "asciidoc/examples/website/layout1.css", "asciidoc/examples/website/layout2.conf", "asciidoc/examples/website/layout2.css", "asciidoc/examples/website/manpage.html", "asciidoc/examples/website/manpage.txt", "asciidoc/examples/website/music-filter.html", "asciidoc/examples/website/music-filter.txt", "asciidoc/examples/website/music1.abc", "asciidoc/examples/website/music1.png", "asciidoc/examples/website/music2.ly", "asciidoc/examples/website/music2.png", "asciidoc/examples/website/newlists.txt", "asciidoc/examples/website/newtables.txt", "asciidoc/examples/website/README-website.html", "asciidoc/examples/website/README-website.txt", "asciidoc/examples/website/README.html", "asciidoc/examples/website/README.txt", "asciidoc/examples/website/sample1.png", "asciidoc/examples/website/sample3.png", "asciidoc/examples/website/sample4.png", "asciidoc/examples/website/source-highlight-filter.html", "asciidoc/examples/website/source-highlight-filter.txt", "asciidoc/examples/website/support.html", "asciidoc/examples/website/support.txt", "asciidoc/examples/website/toc.js", "asciidoc/examples/website/userguide.html", "asciidoc/examples/website/userguide.txt", "asciidoc/examples/website/version83.txt", "asciidoc/examples/website/version9.html", "asciidoc/examples/website/version9.txt", "asciidoc/examples/website/xhtml11-manpage.css", "asciidoc/examples/website/xhtml11-quirks.css",
      "asciidoc/examples/website/xhtml11.css", "asciidoc/filters", "asciidoc/filters/code", "asciidoc/filters/code/code-filter-readme.txt", "asciidoc/filters/code/code-filter-test.txt", "asciidoc/filters/code/code-filter.conf", "asciidoc/filters/code/code-filter.py", "asciidoc/filters/graphviz", "asciidoc/filters/graphviz/asciidoc-graphviz-sample.txt", "asciidoc/filters/graphviz/graphviz-filter.conf", "asciidoc/filters/graphviz/graphviz2png.py", "asciidoc/filters/music", "asciidoc/filters/music/music-filter-test.txt", "asciidoc/filters/music/music-filter.conf", "asciidoc/filters/music/music2png.py", "asciidoc/filters/source", "asciidoc/filters/source/source-highlight-filter-test.txt", "asciidoc/filters/source/source-highlight-filter.conf", "asciidoc/help.conf", "asciidoc/html4.conf", "asciidoc/images", "asciidoc/images/highlighter.png", "asciidoc/images/icons", "asciidoc/images/icons/callouts", "asciidoc/images/icons/callouts/1.png", "asciidoc/images/icons/callouts/10.png", "asciidoc/images/icons/callouts/11.png", "asciidoc/images/icons/callouts/12.png", "asciidoc/images/icons/callouts/13.png", "asciidoc/images/icons/callouts/14.png", "asciidoc/images/icons/callouts/15.png", "asciidoc/images/icons/callouts/2.png", "asciidoc/images/icons/callouts/3.png", "asciidoc/images/icons/callouts/4.png", "asciidoc/images/icons/callouts/5.png", "asciidoc/images/icons/callouts/6.png", "asciidoc/images/icons/callouts/7.png", "asciidoc/images/icons/callouts/8.png", "asciidoc/images/icons/callouts/9.png", "asciidoc/images/icons/caution.png", "asciidoc/images/icons/example.png", "asciidoc/images/icons/home.png", "asciidoc/images/icons/important.png", "asciidoc/images/icons/next.png", "asciidoc/images/icons/note.png", "asciidoc/images/icons/prev.png", "asciidoc/images/icons/README", "asciidoc/images/icons/tip.png", "asciidoc/images/icons/up.png", "asciidoc/images/icons/warning.png", "asciidoc/images/smallnew.png", "asciidoc/images/tiger.png", "asciidoc/INSTALL", "asciidoc/install-sh", "asciidoc/INSTALL.txt", "asciidoc/javascripts", "asciidoc/javascripts/ASCIIMathML.js", "asciidoc/javascripts/LaTeXMathML.js", "asciidoc/javascripts/toc.js", "asciidoc/lang-es.conf", "asciidoc/latex.conf", "asciidoc/Makefile.in", "asciidoc/README", "asciidoc/README.txt", "asciidoc/stylesheets", "asciidoc/stylesheets/docbook-xsl.css",
      "asciidoc/stylesheets/xhtml11-manpage.css", "asciidoc/stylesheets/xhtml11-quirks.css", "asciidoc/stylesheets/xhtml11.css", "asciidoc/text.conf", "asciidoc/vim", "asciidoc/vim/ftdetect", "asciidoc/vim/ftdetect/asciidoc_filetype.vim", "asciidoc/vim/syntax", "asciidoc/vim/syntax/asciidoc.vim", "asciidoc/wordpress.conf", "asciidoc/xhtml11-quirks.conf", "asciidoc/xhtml11.conf",
      
      "source-highlight/ada.lang", "source-highlight/bib.lang", "source-highlight/bison.lang", "source-highlight/c.lang", "source-highlight/c_comment.lang", "source-highlight/c_string.lang", "source-highlight/caml.lang", "source-highlight/changelog.lang", "source-highlight/clike_vardeclaration.lang", "source-highlight/cpp.lang", "source-highlight/csharp.lang", "source-highlight/css.lang", "source-highlight/css_common.outlang", "source-highlight/default.css", "source-highlight/default.lang", "source-highlight/default.style", "source-highlight/desktop.lang", "source-highlight/diff.lang", "source-highlight/docbook.outlang", "source-highlight/esc.outlang", "source-highlight/esc.style", "source-highlight/extreme_comment.lang", "source-highlight/extreme_comment2.lang", "source-highlight/extreme_comment3.lang", "source-highlight/fixed-fortran.lang", "source-highlight/flex.lang", "source-highlight/fortran.lang", "source-highlight/function.lang", "source-highlight/glsl.lang", "source-highlight/haxe.lang", "source-highlight/html.lang", "source-highlight/html.outlang", "source-highlight/html_common.outlang",
      "source-highlight/html_notfixed.outlang", "source-highlight/html_ref.outlang", "source-highlight/htmlcss.outlang", "source-highlight/htmltable.outlang", "source-highlight/htmltablelinenum.outlang", "source-highlight/java.lang", "source-highlight/javadoc.outlang", "source-highlight/javascript.lang", "source-highlight/key_string.lang", "source-highlight/lang.map", "source-highlight/langdef.lang", "source-highlight/latex.lang", "source-highlight/latex.outlang", "source-highlight/latexcolor.outlang", "source-highlight/ldap.lang", "source-highlight/log.lang", "source-highlight/logtalk.lang", "source-highlight/lsm.lang", "source-highlight/lua.lang", "source-highlight/m4.lang", "source-highlight/makefile.lang", "source-highlight/nohilite.lang", "source-highlight/number.lang", "source-highlight/outlang.lang", "source-highlight/outlang.map", "source-highlight/pascal.lang", "source-highlight/perl.lang",
      "source-highlight/php.lang", "source-highlight/postscript.lang", "source-highlight/prolog.lang", "source-highlight/properties.lang", "source-highlight/python.lang", "source-highlight/ruby.lang", "source-highlight/scala.lang", "source-highlight/script_comment.lang", "source-highlight/sh.lang", "source-highlight/slang.lang", "source-highlight/sml.lang", "source-highlight/source-highlight", "source-highlight/spec.lang", "source-highlight/sql.lang", "source-highlight/style.defaults", "source-highlight/style.lang", "source-highlight/style2.style", "source-highlight/style3.style", "source-highlight/symbols.lang", "source-highlight/tcl.lang", "source-highlight/texinfo.outlang", "source-highlight/texinfo.style", "source-highlight/universal-darwin9.0", "source-highlight/universal-darwin9.0/source-highlight", "source-highlight/url.lang", "source-highlight/xhtml.outlang", "source-highlight/xhtml_common.outlang", "source-highlight/xhtml_notfixed.outlang", "source-highlight/xhtmlcss.outlang", "source-highlight/xhtmltable.outlang", "source-highlight/xml.lang", "source-highlight/xorg.lang"
  ]
end
